export const COURSES = [
  // Professional Courses
  { id: 'it', name: 'IT', arabicName: 'الإعلام الآلي', category: 'professional' },
  { id: 'programming', name: 'Programming', arabicName: 'البرمجة', category: 'professional' },
  { id: 'cybersecurity', name: 'Cyber Security', arabicName: 'الأمن السيبراني', category: 'professional' },
  { id: 'webdev', name: 'Web Development', arabicName: 'برمجة المواقع', category: 'professional' },
  { id: 'video-editing', name: 'Video Editing', arabicName: 'مونتاج الفيديو', category: 'professional' },
  { id: 'graphic-design', name: 'Graphic Design', arabicName: 'التصميم الجرافيكي', category: 'professional' },
  { id: 'digital-marketing', name: 'Digital Marketing', arabicName: 'التسويق الرقمي', category: 'professional' },
  { id: 'photography', name: 'Photography', arabicName: 'التصوير الفوتوغرافي', category: 'professional' },
  { id: 'accounting', name: 'Accounting', arabicName: 'المحاسبة', category: 'professional' },
  { id: 'trading', name: 'Trading', arabicName: 'التداول', category: 'professional' },
  { id: 'project-management', name: 'Project Management', arabicName: 'إدارة المشاريع', category: 'professional' },
  
  // Language Courses
  { id: 'english', name: 'English', arabicName: 'الإنجليزية', category: 'language' },
  { id: 'french', name: 'French', arabicName: 'الفرنسية', category: 'language' },
  { id: 'spanish', name: 'Spanish', arabicName: 'الإسبانية', category: 'language' },
  { id: 'italian', name: 'Italian', arabicName: 'الإيطالية', category: 'language' },
  { id: 'russian', name: 'Russian', arabicName: 'الروسية', category: 'language' },
  { id: 'german', name: 'German', arabicName: 'الألمانية', category: 'language' },
];

export const WILAYAS = [
  { code: '01', name: 'Adrar' },
  { code: '02', name: 'Chlef' },
  { code: '03', name: 'Laghouat' },
  { code: '04', name: 'Oum El Bouaghi' },
  { code: '05', name: 'Batna' },
  { code: '06', name: 'Béjaïa' },
  { code: '07', name: 'Biskra' },
  { code: '08', name: 'Béchar' },
  { code: '09', name: 'Blida' },
  { code: '10', name: 'Bouira' },
  { code: '11', name: 'Tamanrasset' },
  { code: '12', name: 'Tébessa' },
  { code: '13', name: 'Tlemcen' },
  { code: '14', name: 'Tiaret' },
  { code: '15', name: 'Tizi Ouzou' },
  { code: '16', name: 'Algiers' },
  { code: '17', name: 'Djelfa' },
  { code: '18', name: 'Jijel' },
  { code: '19', name: 'Sétif' },
  { code: '20', name: 'Saïda' },
  { code: '21', name: 'Skikda' },
  { code: '22', name: 'Sidi Bel Abbès' },
  { code: '23', name: 'Annaba' },
  { code: '24', name: 'Guelma' },
  { code: '25', name: 'Constantine' },
  { code: '26', name: 'Médéa' },
  { code: '27', name: 'Mostaganem' },
  { code: '28', name: "M'Sila" },
  { code: '29', name: 'Mascara' },
  { code: '30', name: 'Ouargla' },
  { code: '31', name: 'Oran' },
  { code: '32', name: 'El Bayadh' },
  { code: '33', name: 'Illizi' },
  { code: '34', name: 'Bordj Bou Arréridj' },
  { code: '35', name: 'Boumerdès' },
  { code: '36', name: 'El Tarf' },
  { code: '37', name: 'Tindouf' },
  { code: '38', name: 'Tissemsilt' },
  { code: '39', name: 'El Oued' },
  { code: '40', name: 'Khenchela' },
  { code: '41', name: 'Souk Ahras' },
  { code: '42', name: 'Tipaza' },
  { code: '43', name: 'Mila' },
  { code: '44', name: 'Aïn Defla' },
  { code: '45', name: 'Naâma' },
  { code: '46', name: 'Aïn Témouchent' },
  { code: '47', name: 'Ghardaïa' },
  { code: '48', name: 'Relizane' },
];

export const EDUCATION_LEVELS = [
  'طالب جامعي',
  'عامل مؤسسة',
  'صاحب مؤسسة',
  'عاطل عن العمل',
  'غير ذلك'
];

export const LANGUAGE_LEVELS = [
  { id: 'a1', name: 'A1', description: 'مبتدئ - Beginner' },
  { id: 'a2', name: 'A2', description: 'أساسي - Elementary' },
  { id: 'b1', name: 'B1', description: 'متوسط - Intermediate' },
  { id: 'b2', name: 'B2', description: 'متوسط عالي - Upper Intermediate' },
  { id: 'c1', name: 'C1', description: 'متقدم - Advanced' },
  { id: 'c2', name: 'C2', description: 'إتقان - Proficiency' },
  { id: 'native', name: 'Native', description: 'لغة أم - Native Speaker' },
  { id: 'none', name: 'None', description: 'لا أتحدث اللغة - No Knowledge' }
];

export const TEACHING_LANGUAGES = [
  'الإنجليزية - English',
  'الفرنسية - French',
  'الإسبانية - Spanish',
  'الإيطالية - Italian',
  'الألمانية - German',
  'الروسية - Russian',
  'العربية - Arabic',
  'محاسبة – Accounting',
  'إدارة أعمال – Business Management',
  'تسويق رقمي – Digital Marketing',
  'تداول – Trading',
  'الاقتصاد الشخصي – Personal Finance',
  'برمجة – Programming',
  'برمجة جافاسكربت – JavaScript Programming',
  'برمجة بايثون – Python Programming',
  'تطوير مواقع – Web Development',
  'تطوير تطبيقات موبايل – Mobile App Development',
  'الذكاء الاصطناعي – Artificial Intelligence (AI)',
  'علوم البيانات – Data Science',
  'الأمن السيبراني – Cybersecurity',
  'تصميم جرافيك – Graphic Design',
  'تصميم داخلي – Interior Design',
  'مونتاج فيديو – Video Editing',
  'تصوير فوتوغرافي – Photography'
];

export const STAFF_FIELDS = [
  'التسويق - Marketing',
  'النظافة - Cleaning',
  'الاستقبال - Reception',
  'الإدارة - Administration',
  'الدعم التقني - Technical Support',
  'المحاسبة - Accounting',
  'الأمن - Security',
  'الصيانة - Maintenance'
];